DMTF/Redfish-Tools

license.txt
odata-csdl-validator/odata_validator.py

Made a change to so that if a directory is being tested, use the schema files found in the directory if they exist instead of trying to access them remotely. This is so that if someone is updating several files (or files referencing changes not yet published), it won't fail the checks in the updated files.

CSDL Validator: Use local schema files if available

---

csdl-to-json-convertor/Utilities.py
csdl-to-json-convertor/service.py

The string used in the Validation.Pattern term within CSDL does not escape slashes (nor should it). However, when converting to JSON, the slashes used in some of the regex strings need to be escaped to conform to JSON string formatting rules.

CSDL to JSON: Added escaping slashes when generating the "pattern" property

---

csdl-to-json-convertor/service.py

Currently only Redundancy_v1.xml hits this issue, so this will correct the generation of Redundancy.json.

Added support for generating JSON definitions for schemas that only define referenceable members

---

odata-csdl-validator/odata_validator.py

Added retries when a connection is reset when downloading a remote schema file.
Fix #46

Fix #46: Added retries when connection is reset by peer

---

odata-csdl-validator/odata_validator.py

Added check to fail schema validation if a NavigationProperty of type Collection uses Nullable

Nullable check for Navigation Properties

---

odata-csdl-validator/odata_validator.py

Based on some wording in section 4.5 of the CSDL spec, it sounds like this sort of nesting technically isn't allowed, but Org.OData.Capabilities.V1.xml does this nesting. Currently following up with @mikepizzo and @wfayed about this, but queuing the change if this is supposed to be allowed and the spec just needs some clarification.
Fix #44

Allowing for nested ComplexTypes for Vocabulary Terms

---

csdl-to-json-convertor/service.py

Adds the property "enumDeprecated" to the definition for an enum. For example...
```
"LineInputVoltageType": {
"type": "string",
"enum": [
"Unknown",
"ACLowLine",
"ACMidLine",
"ACHighLine",
"DCNeg48V",
"DC380V",
"AC120V",
"AC240V",
"AC277V",
"ACandDCWideRange",
"ACWideRange",
"DC240V"
],
"enumDescriptions": {
"Unknown": "The power supply line input voltage type cannot be determined.",
"ACLowLine": "100-127V AC input. Deprecated: Use AC120V.",
"ACMidLine": "200-240V AC input. Deprecated: Use AC240V.",
"ACHighLine": "277V AC input. Deprecated: Use AC277V.",
"DCNeg48V": "-48V DC input.",
"DC380V": "High Voltage DC input (380V).",
"AC120V": "AC 120V nominal input.",
"AC240V": "AC 240V nominal input.",
"AC277V": "AC 277V nominal input.",
"ACandDCWideRange": "Wide range AC or DC input.", …
```

Added support for processing Redfish.Deprecated on enum members

---

csdl-to-json-convertor/service.py

Pattern used by the tool did not match the OData "Edm.Guid" regex
pattern nor the definition from RFC 4122.

Corrected pattern for UUID to match RFC and OData

---

csdl-to-json-convertor/service.py

Not entirely sure why some of the stubbed references are being cached when processing entities that have no references to them, but this will fix abstract types from inadvertently adding them to their anyOf array when it doesn't make sense to do so.

Changed base type check to not assume non-processed entities are valid base types

---

doc-generator/doc_formatter/html_generator.py

Added HTML <nobr> no-break tags around "read-only" and "read-write"
column text to reduce excess blank lines in tables.  Added no-break
around Property Name and version so that array markers don't wrap.

Added HTML no-break tags for some table values

---

doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py

Include H1 headings in TOC, bump up heading levels in schema fragments, move the closing brace for an object into the first column of the last row of that object (instead of in a row by itself).

Doc generator formatting tweaks (HTML output)

---

csdl-to-json-convertor/csdl-to-json.py

Two changes:
- Backing out etag addition (since OData schema from SPMF has not been published to support the change)
- Added change to copy enum definitions in unversioned namespaces to versioned namespaces to help resolve things with the doc generator

Some workarounds for SNIA to help with their release

---

doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py

Had incorrect capitalization of 'target' (shown as 'Target').
Fix #105

Corrected name of 'target' Action property

---

doc-generator/doc_formatter/csv_generator.py
doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py

This applies to property names and also the order of schemas (note position of VLanInterface).

Use case-insensitive sort throughout. Fixes #114.

---

doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py
doc-generator/doc_gen_util/doc_gen_util.py
doc-generator/doc_generator.py
doc-generator/parse_supplement.py
doc-generator/sample_inputs/usersupplement.md
doc-generator/tests/test_supplement_output.py
doc-generator/tests/test_version_deprecated.py

This addresses: 
> Allow complete description text replacement for Properties and a
> description override tag that indicates the doc generator should use
> this description text “as is” for final output in both full schemas
> and schema fragments.
> 
> Ensure description text replacement works within JSON objects as well
> as at the root level.
Complete description text replacement can be specified in a "FullDescription Overrides" section in the supplemental markdown fed to the doc generator. Semantics are identical to the "Description Overrides" section.

Improvements to property description overrides

---

doc-generator/README.md

Updated README to:
* Correct location for Python Markdown.
* Clarify which directory you must be in to run requirements.txt.
* Fix some typos.
* Clarify location of usersupplement.md.
@jautor

Fix doc_generator README file

---

doc-generator/README.md

The path to the supplemental file was incorrect. I fixed it.
Also, clarified tool by calling it `doc_generator.py`, to distinguish it from parent directory, `doc-generator`.
@jautor

[DIANE] Fix path to supplemental file

---

odata-csdl-validator/odata_validator.py

Two extensions:
1) added additional error output when an xml file cant be parsed.
--prints the exception error info
--if its bad xml syntax, it tells the line and column where the syntax failed
2) handles relative links inside an xml csdl file.
eg:    I am valicating  https://github/pathTo/IntelRackScaleOem.xml which contains links to many more schemas in the remote directory path as the root file I am validating.  Its links look like:
<edmx:Reference Uri="Resource_v1.xml">  where the assumption is Resource_v1.xml
I see other oem csdl files with internal links eg /redfish/v1/Schemastore/Resource_v1.xml
where the referenced links are under the same <scheme>/<netloc>/.  This should work for them too.
The current change only applies if the target starts with http.
It explicitly does not …

added  error info re where in xml parse error was, and support for relative url inside xml files

---

odata-csdl-validator/odata_validator.py

The OData 4.0 errata 3 schemas (for whatever reason) point back to the original core schema (as opposed to the errata version), which has a bug in it.

Workaround for OData Core Schema bug

---

.gitignore
doc-generator/doc_generator.py

This affected definitions in schemas that were not versioned at the "top" object for the file, but
rather at individual properties or definitions, and that further had an "anyOf" specifying a definition
that went straight to an enum. More generally, this would probably affect any pointer to a definition that
did not specify an object with properties. Example: AddressOrigin in IPAddresses/IPv4Address.

Fix a bug wherein enums were dropped for some properties of common objects.

---

.travis.yml
doc-generator/Pipfile
doc-generator/doc_generator.py

Schema traverser didn't have data to get to some properties defined in the unversioned schemas. Now it does. 
(There's also a little unrelated updated config here for my Mac and travis.)

Fix an issue affecting docs for the 2018.3 schemas

---

doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py
doc-generator/doc_gen_util/doc_gen_util.py
doc-generator/doc_generator.py
doc-generator/tests/samples/payloads/ActionInfo-v1-example.json
doc-generator/tests/samples/payloads/LogService-v1-example.json
doc-generator/tests/samples/payloads/Memory-v1-example.json
doc-generator/tests/samples/payloads/SomeOtherFile.txt
doc-generator/tests/test_payload_directory.py

Implemented just as described in the issue. Payloads for Action examples are a new feature; they are simply included with the Action details -- immediately above in the case of markdown output; immediately below for HTML output.

Doc generator: include json payloads from a specified directory (fixes #127)

---

doc-generator/README_Property_Index.md
doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/property_index_generator.py
doc-generator/doc_generator.py
doc-generator/tests/samples/referenced_objects/network_sample_output/index.html
doc-generator/tests/test_openapi.py

Adds support for a boilerplate input file (--sup argument) in Property Index mode. 
URI formatting improvements in HTML mode include zero-width spaces after slashes, providing reasonable places to break a long line if necessary, and style rules to provide a "hanging indent" appearance when a URI is wrapped.

Updates to doc generator -- Property Index boilerplate and better URI formatting

---

redfish-repo-test/csdl-syntax-test.js

Numerous outlet/plug types have underscores for clarity (no better option - open to any suggestions, though).

Added DCIM enumerations to whitelist

---

csdl-to-json-convertor/csdl-to-json.py

Allow for comma-separated list of excerpt names in the "Redfish.Excerpt" annotation to support properties that appear in multiple excerpts.

Added multiple excerpt support

---

csdl-to-json-convertor/README.md
csdl-to-json-convertor/csdl-to-json.py
csdl-to-json-convertor/dmtf-config.json
json-to-openapi-converter/README.md
json-to-openapi-converter/dmtf-config.json
json-to-openapi-converter/json-to-yaml.py
redfish-repo-test/csdl-syntax-test.js
redfish-repo-test/openapi-test.js
redfish-repo-test/package.json

Fix #260; added a DoNotWrite option in the config files for the converter tools so the output doesn't need to be manually pruned.
More Swordfish files being whitelisted.
Bumped the OpenAPI validation timeout.

Repo test and converter tool updates

---

redfish-repo-test/csdl-syntax-test.js

The Swordfish schemas still have mays in them. Would like to have them fix that though. This change allows DMTF repo to ignore Swordfish schema with a config change.

Skip new tests on external schemas

---

json-to-openapi-converter/dmtf-config.json
json-to-openapi-converter/json-to-yaml.py

Most of the OpenAPI tooling flattens the entire definition list. It seems that they rely on a recommendation from JSON Schema where names of definitions should be unique. Some of our resources have structure names that are reused (Links for example), and the resources themselves will collide simply because of our versioning methodology. This change prepends all type definitions with the schema file name and version string to ensure uniqueness everywhere.

OpenAPI Rename Types

---

doc-generator/doc_formatter/doc_formatter.py
doc-generator/tests/samples/readwrite_links/Facility/Facility.json
doc-generator/tests/samples/readwrite_links/Facility/Facility.v1_0_1.json
doc-generator/tests/samples/readwrite_links/Facility/FacilityCollection.json
doc-generator/tests/samples/readwrite_links/Facility/Resource.json
doc-generator/tests/samples/readwrite_links/Facility/Resource.v1_0_0.json
doc-generator/tests/samples/readwrite_links/Facility/Resource.v1_6_0.json
doc-generator/tests/samples/readwrite_links/Facility/odata-v4.json
doc-generator/tests/samples/readwrite_links/Facility/odata.v4_0_2.json
doc-generator/tests/test_readwrite_links.py

There were two issues here: 
1) When gathering data for a $ref in an "items" object, the doc generator wasn't carrying through the "readonly" value from the parent object. 
2) Similarly, when not in an "items" object, the "readonly" value was just plain being set to True when constructing data to present as a Link. (The doc generator cobbles together a basic summary object in this case, and probably when I initially wrote this I had the incorrect impression that links weren't writable.)

Carry through readonly data to links, items. Fixes #296

---

csdl-to-json-convertor/README.md
csdl-to-json-convertor/csdl-to-json.py
json-to-openapi-converter/README.md
json-to-openapi-converter/json-to-yaml.py

Core definitions like Resource, OData definitions, and Redfish JSON Schema extensions all have hardened URIs for their latest versions. It's not longer needed to have this specified as a config file argument, which could result in older config files referencing stale documents.

Removed some config file settings that should no longer be overridden

---

redfish-repo-test/csdl-syntax-test.js
redfish-repo-test/package.json

This checks for must in long descriptions. It also checks for plural entity and complex types as those are the exception, not the rule.
For types that we want to allow we can temporarily allow them in the project specific config files until they get merged here.

Add tests for must in long descriptions and plural types

---

doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/markdown_generator.py
doc-generator/tests/samples/generate_docs_cases/general/expected_output/markdown_output.md
doc-generator/tests/samples/generate_docs_cases/integer/expected_output/markdown_output.md
doc-generator/tests/samples/generate_docs_cases/required/expected_output/markdown_output.md

Two unrelated corrections: 
* Improve the links produced for excerpts that are moved into the Property Details section (due to combining of multiple references)
* Correct the heading levels of some recently-added headings in the markdown format.

Doc generator updates: excerpt links and heading levels

---

redfish-repo-test/csdl-syntax-test.js
redfish-repo-test/package.json

Expects mockups to be named "ABCRequest.json" and "ABCResponse.json" to signify that the mockup is for an action payload, which is not expected to contain `@odata.type`

Added support to allow for action request and response mockups to not contain @odata.type

---

redfish-repo-test/csdl-syntax-test.js

This allows a project to include a temporary local addition to non-Pascal Cased enums before it gets added permanently to the tool

Allow local additions to non-PascalCased Enums

---

doc-generator/doc_formatter/doc_formatter.py

Removed the combination of property and enum type descriptions which was used when collapsing array properties into a single line.  The combination may have been necessary in early schema where descriptions were not fully populated, but this now creates duplicate text.

Removed description combination

---

redfish-repo-test/helpers/updatetables.js
redfish-repo-test/package.json

Based off of a configured list of documents, the script finds all instances of table markers, updates the table number and references. Allows us to insert and remove tables without having to manually update all other tables.

Added helper script to update table numbers in documents

---

redfish-repo-test/helpers/updatemockups.js
redfish-repo-test/package.json

Scans the mockups directory and performs the following:
- Corrects the placement of `@odata.id` and `@Redfish.Copyright` to be at the bottom of every mockup (this is a pattern all of our published mockups follow)
- Updates copyright strings
- Updates `@odata.type` and namespace references in $metadata to reference the latest schema versions

Added tool to automatically update mockups

---

csdl-to-json-convertor/csdl-to-json.py

A few issues raised (primarily in the OpenAPI tooling) with how some of our Resource files are generated. Two things noticed:
* Our top-level definitions for Resource, ResourceCollection, and ReferenceableMember don't follow the anyOf pattern we use elsewhere; essentially they're fixed on the 1.0.0 definition, which is broken
* References in Resource.json to other things in Resource.json are all using external links instead of internal links

CSDL to JSON Schema Resource conversion fixes

---

redfish-repo-test/helpers/updatemockups.js

Encountered some mockups where a lot of things moved around, and the script did not properly handle cases where the last line does not originally have a comma and needs one, or does have one and needs it removed.

Fixed updatemockups script where a comma needs to be inserted or removed at the end of the file

---

.travis.yml
doc-generator/Pipfile
doc-generator/README_config_files.md
doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/markdown_generator.py
doc-generator/doc_generator.py
doc-generator/tests/samples/generate_docs_cases/general/expected_output/index.html
doc-generator/tests/samples/generate_docs_cases/general/expected_output/markdown_output.md
doc-generator/tests/samples/generate_docs_cases/general/expected_output/markdown_with_table_numbering_output.md
doc-generator/tests/samples/generate_docs_cases/general/expected_output/slate_output.md
doc-generator/tests/samples/generate_docs_cases/integer/expected_output/markdown_output.md
doc-generator/tests/samples/generate_docs_cases/integer/expected_output/slate_output.md
doc-generator/tests/samples/generate_docs_cases/normative/expected_output/index.html
doc-generator/tests/samples/generate_docs_cases/required/expected_output/markdown_output.md
doc-generator/tests/samples/generate_docs_cases/required/expected_output/slate_output.md
doc-generator/tests/samples/pattern_properties/expected_output/MessagesPropertyDetails.md
doc-generator/tests/samples/referenced_objects/network_sample_output/output.md
doc-generator/tests/test_generate_docs.py

Adds a "with_table_numbering" config option (boolean, to be specified in the config file) to turn on the ISO table numbering feature. Default is off; option is ignored for HTML output.

Make "numbered" table headings optional. Fixes #335

---

doc-generator/doc_formatter/markdown_generator.py
doc-generator/tests/samples/fragments/CommonPropertySchema.json
doc-generator/tests/samples/fragments/expected_output.html
doc-generator/tests/samples/fragments/expected_output.md
doc-generator/tests/samples/fragments/expected_slate_output.md
doc-generator/tests/samples/fragments/json-schema/IntegerTest.json
doc-generator/tests/samples/fragments/json-schema/IntegerTest.v1_0_0.json
doc-generator/tests/samples/fragments/json-schema/Resource.json
doc-generator/tests/samples/fragments/json-schema/Resource.v1_6_0.json
doc-generator/tests/samples/fragments/json-schema/odata.v4_0_1.json
doc-generator/tests/samples/fragments/json-schema/odata.v4_0_2.json
doc-generator/tests/samples/fragments/json-schema/odata.v4_0_3.json
doc-generator/tests/test_fragments.py

Markdown mode fragments were coming out slate-style, as it's the default if
output_format is not specified.

Carry over output_format config value to fragment generator.

---

doc-generator/doc_formatter/markdown_generator.py

Markdown will combine lines with simple newline characters - adding the HTML break is a better solution than a double newline.

Add line break at end of all URIs

---

doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py
doc-generator/locale/doc_generator.pot
doc-generator/tests/samples/action_payloads/expected_output/markdown.md
doc-generator/tests/samples/action_payloads/expected_output/slate.md
doc-generator/tests/test_openapi.py

Changes a couple of heading levels and brings across the summarized Action URI format from HTML mode.

Markdown mode tweaks for Actions

---

doc-generator/format_utils/format_utils.py

Swordfish has moved to a pandoc-only documentation approach, which requires some changes to the generated syntax that handle the sequencing and references to generated tables. 
Closes #377

Update table reference / link syntax

---

doc-generator/doc_formatter/doc_formatter.py

Adding a non-printable whitespace/break character between all URI segments in the output to allow for document conversion tools to better process line wrapping on long URIs.  This occurs primarily in the Resource Collection URI section as the URIs are in a two-column table.

Added non-printable space for URI line wrapping

---

csdl-to-json-convertor/csdl-to-json.py

Filling a gap for how clients can find OEM action definitions in JSON Schema. This is due to how action definitions are typically bundled with the resource definition, but in the case of OEM actions, they're broken apart. The patterns being set forth is with OEM actions, the unversioned JSON Schema file will contain an anyOf statement to point to the specific versions.

OEM action handling for JSON Schema

---

doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py

Enum processing incorrectly assumed "subset" would be defined for an enum in subset mode. It's optional (absent means "include all").

Doc generator: fix for crash bug in subset mode

---

doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py
doc-generator/doc_formatter/property_index_generator.py
doc-generator/tests/samples/action_payloads/expected_output/output.html
doc-generator/tests/test_action_payloads.py

Interprets subset paths (from user-defined subset config) in the context of the schema currently being documented, which we DocFormatter was already tracking as part of self.this_section. Previously, the paths were being looked up in the context of the schema where the property was defined, which is less useful to authors.

Doc generator: use a where-used approach to interpreting subset config. Fixes #406

---

redfish-repo-test/csdl-syntax-test.js

Ensures `Action` definitions in CSDL contain `IsBound="true"` and the first parameter references the binding actions object.

Added check for binding parameter presence in all actions

---

doc-generator/doc_formatter/doc_formatter.py

Schema files that do not have resource definitions (like Redundancy) are not mapped the into internal data structures the same way as resource definitions (like ComputerSystem) are. The method `get_supplemental_details` takes a schema reference tag and converts it to schema definitions, but if there is no mapping, then no supplemental info is pulled.
The change here allows a config file to directly specify the schema reference when describing supplemental info. For example, the following will allow the `HealthRollup` property in the common `Status` object to have supplemental text inserted:
```
{
...
"schema_supplement": {
"ComputerSystem": {
"property_details": {
"UUID": "<Additional UUID text>"
}
},
"redfish.dmtf.org/schemas/v1/Resource.json": {
"property_details": {
"HealthRollup": …
```

Added alternative method for looking up supplemental info for properties

---

odata-csdl-validator/README.md
odata-csdl-validator/odata_validator.py
odata-csdl-validator/redfish-rules.json

Fix #439 
* Added validation that a reference URI is not specified multiple times in a single file
* Added back validation of annotation term usage with 'AppliesTo', but allow for certain cases where we expect to deviate from the definition

Additional CSDL validation

---

csdl-to-json-convertor/csdl-to-json.py

* Added start/end markers to enforce the pattern for the entire property value
* Removed usage of "negative" duration values, which are not allowed per the Redfish spec

Correcting regex patterns inserted for some CSDL types

---

.gitignore
doc-generator/README_config_files.md
doc-generator/doc_formatter/csv_generator.py
doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_formatter/html_generator.py
doc-generator/doc_formatter/markdown_generator.py
doc-generator/doc_formatter/property_index_generator.py
doc-generator/doc_generator.py
doc-generator/sample_inputs/standard_html/config.json

Also, trim `ResourceBlock` related URIs from the URI list for brevity, but add a note to the URI list to explain that.

Doc-generator - Add detection of deprecated URIs

---

.gitignore
doc-generator/doc_formatter/doc_formatter.py
doc-generator/doc_generator.py

In Subset and Profile modes, handling of "link" properties (which are objects with a single `@odata.id` property) is incorrect and difficult to unravel fixes.  When combined with the "terse" profile mode, link properties with simple mandatory requirements - and notated simply in the profile document as an empty object, as in:
```
"EnvironmentMetrics": {}
```
are expanded to include every property in the linked schema (the profile default being "if not specified, everything inside is required").  This may need to be further clarified in the profile specification.  
The fixes here will at least give an escape for subset mode to show the single property within those link property objects.  And for profiles, the requirements of the "parent" schema were being incorrectly applied to the child …

Fixes and partial fixes for Profile and Subset output

---

json-to-openapi-converter/json-to-yaml.py

If a user has pyyaml 6.0 or higher, they will hit an exception when trying to extend an existing openapi.yaml file. Pyyaml made a breaking change that requires consumers to specify the type of YAML loader. This argument is supported in older versions of pyyaml, so this won't break existing users for us.

Added explicit inclusion of the YAML loader argument for pyyaml 6.0

---

json-to-openapi-converter/json-to-yaml.py

When loading from a base OpenAPI file, an exception is raised when processing the /redfish/v1/$metadata entry due to the lack of an "application/json" entry under "content". The change here just skips over non-JSON URIs with the expectation that they will be added back later. If we ever grow beyond just /redfish/v1/$metadata as the only non-JSON thing to capture in openapi.yaml, we might need to revisit this.

Skip non-JSON URIs when loading from a base OpenAPI file

---

csdl-to-json-convertor/csdl-to-json.py

Two changes:
* When building the "anyOf" statement for the unversioned schema, it was comparing namespace versions incorrectly and applying the action for all schema versions.
* When building the name of the action for the Actions property, use the name of the binding parameter to generate the name. Some OEMs use common action definitions for OEM resources; while this isn't a normal practice for standard Redfish resources, it is being used for some OEM resources.

Fixes to OEM Action processing when building JSON Schema

---

json-to-openapi-converter/json-to-yaml.py

At least one Swordfish schema file has an empty anyOf usage (FileSystem.json).

Made change to not step into anyOf modifications if there are no entries

---

csdl-to-json-convertor/csdl-to-json.py

Gap was found when reviewing the primitive CSDL types listed in the Redfish Spec; we allow for `Edm.Double`, but do not have it in the conversion process.

Added conversion of Edm.Double to number

---

doc-generator/README.md

@mraineri , I was reading up about the documentation generator, and I saw the old name "spmf". This commit updates "spmf" to "redfish" in the readme, if you think it's worth the change.

replace deprecated name "spmf" with "redfish"

---

doc-generator/doc_formatter/doc_formatter.py

Missing close parenthesis when property version string contains both an "added" and "deprecated" version.

Added missing close parenthesis for version string

---

json-to-openapi-converter/json-to-yaml.py

Fix #464 
@commonism FYI here are the before and after for some properties:
Before...
```
Description:
$ref: http://redfish.dmtf.org/schemas/v1/Resource.yaml#/components/schemas/Resource_Description
nullable: true
readOnly: true
EnvironmentalClass:
$ref: '#/components/schemas/Chassis_v1_25_0_EnvironmentalClass'
description: The ASHRAE Environmental Class for this chassis.
nullable: true
readOnly: false
x-longDescription: This property shall contain the ASHRAE Environmental
Class for this chassis, as defined by ASHRAE Thermal Guidelines for Data
Processing Environments.  These classes define respective environmental
limits that include temperature, relative humidity, dew point, and maximum
allowable elevation.
x-versionAdded: v1_9_0
IPv4StaticAddresses:
description: The IPv4 static …
```

Reformatted  usage to use oneOf to ensure it doesn't collide with the nullable usage

---

csdl-to-json-convertor/csdl-to-json.py

Resource 1.8.3 removed "Name" as an excerpt property, so this workaround isn't needed anymore.

Removed workaround for stub excerpts where 'Name' in Resource used to be tagged as an excerpt

---

json-to-openapi-converter/json-to-yaml.py

Action requests can contain annotations (like `@Redfish.OperationApplyTime`).

Added copying of patternProperties to action request bodies

---

redfish-oem-integrator/redfish-oem-integrator.py

From internal testing, there were two corner cases encountered that would throw exceptions:
* When the config file for a resource has a property marked as "disabled" and it's processing a version of schema for the resource that predates the addition of the property
* When the config file for a resource has an action parameter marked as "disabled" and it's processing a version of schema for the resource that predates the addition of the parameter
In both cases, when the tool tries to update older versions of schema, it encounters KeyError exceptions since the property or parameter doesn't exist. The change made gracefully handles the exception to keep moving on since the term doesn't apply to that version of schema.

Added graceful handling when removing properties and parameters marked as unsupported on older schema versions

---

doc-generator/format_utils/format_utils.py

Split via an extraneous linebreak '\n' character when generating tables via make_table in markdown, as this causes numcells to include subsequent rows.
This may be more adequately fixed at the source in format_property_row, as it only generates a single string as a row with '\n' as a delimiter, line 314
Fix #468
edit:  new output
vs original

Treat new line as row in markdown table generation

---

doc-generator/doc_formatter/doc_formatter.py

Generator now checks if profile object is considered a link, if an object is documented but not from the same schema, or not documented, such as common Resources.
Includes fix to accidental key name replacement from a previous feature addition of UseCases
Fix #447 
edit:  show output example
vs original 
additionally:  fixed line for UseCaseValues
vs original

Removed expansion of profile object links, fix to usecase keyword
