DMTF/Redfish-Tools

.gitignore, csdl-to-json-convertor/service.py
=> Add ability to handle quotes in Description and LongDescription

LICENSE.md, csdl-to-json-convertor/LICENSE.md, odata-csdl-validator/LICENSE.md
Added proper Markdown formatting in license text to make it display more nicely when viewing
=> Added proper Markdown formatting in license text

odata-csdl-validator/odata_validator.py
Added exception handling around file opening to make it clear what file cannot be opened if there is an error
=> Added exception handling around file opening

redfishMockupServer/AUTHORS.md, redfishMockupServer/CHANGELOG.md, redfishMockupServer/LICENSE.md, redfishMockupServer/README.md, redfishMockupServer/redfishMockupServer.py
PR of 0.9.2 changes direct to Master (if we want to do that)
=> Redfish mockup server0.9.2

csdl-to-json-convertor/Utilities.py, csdl-to-json-convertor/service.py, csdl-to-json-convertor/snia-schemas.ini
=> Add ability to specify external schemas in INI file

csdl-to-json-convertor/service.py
Edm.Duration is using the wrong RegEx. This fixes that. 
Also adds the Edm.TimeOfDay time (who's RegEx Edm.Duration was using)
=> Fix Edm.Duration and add Edm.TimeOfDay

odata-csdl-validator/odata_validator.py
Added a try/except block around the call to main() so that if there is a schema error, the tool can exit with something other than 0 returned.
=> Added exception catching to exit with an error

odata-csdl-validator/odata_validator.py
Fix #54 
Added duplicate property/navigation property name checking for complex types
=> Fix54: Duplicate name check within complex types

doc-generator/devsupplement.md, doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py, doc-generator/doc_generator.py, doc-generator/parse_supplement.py, doc-generator/usersupplement.md
Two small updates, addressing issues #60 and #62.
=> Add units mapping, move "nullable" info to the attributes column

doc-generator/doc_formatter/doc_formatter.py
Relaxed searches for "idRef", added 'or' cases.
=> Changed file references tied to odata.4.0.0.json

doc-generator/doc_formatter/doc_formatter.py, doc-generator/parse_supplement.py
This fixes an issue that cropped up in the latest run.
=> Bug fix for excessive recursion in latest batch of schemas

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_generator.py
Better consistency in creating file paths, candidate fix for "anyOf" properties listing multiple versions of the same schema.
=> Doc generator fixes

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py
Generate Action Details section based on Actions with parameters.
=> Add support for Action Details

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py, doc-generator/schema_traverser.py
Add output for Parameters of Actions (this appears as an "Action Details" section after the main schema properties table). 
Also includes a couple of small bug fixes.
=> Add Action Parameters

csdl-to-json-convertor/README.md, csdl-to-json-convertor/csdl-to-json.py, csdl-to-json-convertor/dmtf-config.json
- Added support for converting action parameters
- Added support for deprecating entire enum definitions
- Added "Overwrite" flag to let a user preserve existing versioned JSON files
- Other minor updates
=> Updates to the CSDL to JSON Converter

csdl-to-json-convertor/csdl-to-json.py
=> Added @odata.etag to all resources

doc-generator/doc_formatter/html_generator.py
=> Added default value for enumDescription

csdl-to-json-convertor/README.md, csdl-to-json-convertor/csdl-to-json.py, csdl-to-json-convertor/dmtf-config.json
Updates that were used for the 2018.1 schema bundle
=> CSDL to JSON Updates

odata-csdl-validator/odata_validator.py
=> Added missing protection when verifying scale and precision terms

README.md
I had accidentally left this pointing to lucidmeetings/Redfish-Tools.
=> Update Travis-ci link in README.md

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_generator.py, doc-generator/tests/test_version_deprecated.py
This addresses properties that have been moved from versioned to unversioned schemas.
=> Fold in definitions from unversioned schemas after processing versioned ones

csdl-to-json-convertor/csdl-to-json.py, csdl-to-json-convertor/dmtf-config.json
- Copyright format update
- Use a generic version of the "Redfish Schema" file
- Differentiate Decimal from Integer numbers
- Added capabilities, URIs, and auto expand terms
- Added `@odata.id` and `@odata.type` properties as required
=> CSDL to JSON Updates for 2018.2

doc-generator/doc_gen_util/doc_gen_util.py, doc-generator/doc_generator.py, doc-generator/tests/samples/version_order/ClassOfService.json, doc-generator/tests/samples/version_order/ClassOfService.v1_0_0.json, doc-generator/tests/samples/version_order/ClassOfService.v1_0_1.json, doc-generator/tests/samples/version_order/ClassOfService.v1_0_2.json, doc-generator/tests/samples/version_order/ClassOfService.v1_1_0.json, doc-generator/tests/samples/version_order/ClassOfService.v1_1_1.json, doc-generator/tests/samples/version_order/Resource.json, doc-generator/tests/samples/version_order/Resource.v1_0_0.json, doc-generator/tests/samples/version_order/Resource.v1_6_0.json, doc-generator/tests/samples/version_order/odata.4.0.0.json, doc-generator/tests/test_version_order.py
Fixes an issue where a 1.0 errata version of a schema was being output instead of the latest 1.1 version.
=>  Doc generator: ensure versioned files are sorted by version number when ingesting data.

doc-generator/doc_gen_util/doc_gen_util.py, doc-generator/doc_generator.py
Fixes an error in an apparently rare case, and clears up some warnings.
=> Doc generator: minor maintenance fixes

csdl-to-json-convertor/csdl-to-json.py
=> Added support for mapping of namespace aliases when making external references

.gitignore, csdl-to-json-convertor/csdl-to-json.py, json-to-openapi-converter/dmtf-config.json, json-to-openapi-converter/json-to-yaml.py
Added support for revisions annotation.
Added support for the excerpt term.
Added support for ReturnType.
Fix #160
=> CSDL to JSON and JSON to YAML updates for 2018.3

json-to-openapi-converter/json-to-yaml.py
=> Fixed construction of action response reference

csdl-to-json-convertor/csdl-to-json.py
Addressing an issue raised on the forum:
https://redfishforum.com/thread/171/odata-event-schema-v1-json
=> Added special handling of Event to not add @odata.id or @odata.etag properties

csdl-to-json-convertor/csdl-to-json.py
=> Fixed handling of deprecated term for Properties

doc-generator/schema_traverser.py
Use types.MappingProxyType to guard against accidental changes to data
used by the SchemaTraverser.
This corrects some errant version output I noticed while testing something else, and it guards against making the same mistake again.
=> Doc generator: Use immutable data structures in SchemaTraverser

doc-generator/schema_traverser.py
Use types.MappingProxyType to guard against accidental changes to data
used by the SchemaTraverser.
=> Use immutable data structures in SchemaTraverser

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py, doc-generator/doc_gen_util/doc_gen_util.py, doc-generator/doc_generator.py, doc-generator/sample_inputs/OCPManagedDevice.v1_0_0.json, doc-generator/sample_inputs/OCPRackManagerController.2019.1.json, doc-generator/sample_inputs/SampleProfileWithURIs.json
* Add some sample files for reference
* Support for URIs in profile mode.
* Doc generator: merge Protocol sections from profiles (now that we are using them)
* Apply formatting to URIs in conditional requirements
* Doc generator profile mode: output conditional requirements at resource level, if present.
=> Doc generator: support URIs in profile mode (#3)

doc-generator/README_Property_Index.md, doc-generator/doc_formatter/property_index_generator.py
Assume markdown supplemental file; convert to HTML if HTML mode; add TOC.
=> Doc generator: slight rework to supplement handling for Property index.  Closes #173

json-to-openapi-converter/json-to-yaml.py
=> Added logic to download and check JSON Schema files to ensure an external definition is a resource link vs another type of definition

csdl-to-json-convertor/csdl-to-json.py, doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py, doc-generator/doc_generator.py, doc-generator/tests/test_config_handling.py
"A resource entry with NO “ActionRequirements” indicates that all Actions should be included"
This merge also includes some refactoring of how the doc generator handles its various inputs, and some tests for that.
=> Updates affecting actions in Subset output

redfish-repo-test/csdl-syntax-test.js
Changes made to electrical types which replaced values in whitelist
=> Updated enumeration whitelist

doc-generator/doc_generator.py
partial fix for issue but more work needed.
=> Doc-gen: Update variable name referenced in error messages

redfish-repo-test/csdl-syntax-test.js
=> Changes to test for Yang conversion compatability

doc-generator/doc_formatter/html_generator.py
=> Improve Action Details section for readability

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py
A crash in generating docs for DSP2046 surfaced this issue.
=> Doc generator: bug fix for HTML anchors in fragments

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py, doc-generator/doc_formatter/property_index_generator.py
No new functionality here -- this fixes "unimplemented" errors in the Property Index formatter due to new functions in the DocFormatter class.
=> Doc formatter: update Property Index formatter

redfish-repo-test/package.json
Redfish Repo Test relied on several outdated versions. This updates those versions.
=> Update outdated components

redfish-repo-test/csdl-syntax-test.js
These are changes so that this tool can validate Swordfish schemas.
=> Changes required for swordfish schema tests

redfish-repo-test/csdl-syntax-test.js
=> Added check to ensure all resources specify capabilities

odata-csdl-validator/odata_validator.py
The tool made some assumptions about URIs in the references tags being absolute; made enhancements to be as flexible as possible when trying to find a referenced schema file.
=> Enhanced logic to opening schema files to check for relative URIs

json-to-openapi-converter/dmtf-config.json, json-to-openapi-converter/json-to-yaml.py
* Updated version number of config file for 2020.4
* Added support for flagging integers as int64 in OpenAPI file generation
=> 2020.4 changes

doc-generator/TABLE_NUMBER_README.md, doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/markdown_generator.py, doc-generator/format_utils/format_utils.py, doc-generator/locale/doc_generator.pot, doc-generator/locale/en/LC_MESSAGES/doc_generator.po, doc-generator/table_number.awk, doc-generator/tests/samples/generate_docs_cases/general/expected_output/index.html, doc-generator/tests/samples/generate_docs_cases/general/expected_output/markdown_output.md, doc-generator/tests/samples/generate_docs_cases/general/expected_output/slate_output.md, doc-generator/tests/samples/generate_docs_cases/integer/expected_output/markdown_output.md, doc-generator/tests/samples/generate_docs_cases/integer/expected_output/slate_output.md, doc-generator/tests/samples/generate_docs_cases/normative/expected_output/index.html, doc-generator/tests/samples/generate_docs_cases/required/expected_output/markdown_output.md, doc-generator/tests/samples/generate_docs_cases/required/expected_output/slate_output.md, doc-generator/tests/samples/pattern_properties/expected_output/MessagesPropertyDetails.md, doc-generator/tests/samples/referenced_objects/network_sample_output/output.md, doc-generator/tests/test_release_history.py
This is just for reference. I'm using the command-line approach to merging changes in, which recommends merging directly into master when all issues are resolved. 
The only problem I see with this batch is that the headings for the "release history" tables don't make sense. The old tables lacked headings; they aren't really tabular information. The new tables have a two-column heading, "Version" and "Release." 
Problem is, the "release history" may be one to several columns, each of which contains a version and release.
=> Staged changes for Pull request 324

redfish-repo-test/csdl-syntax-test.js
Adds a check for repeated type checks like the recent issue with CacheMetrics
=> Add repeated type check

csdl-to-json-convertor/csdl-to-json.py
Update tool to use LineOfService as equivalent base_type to Resource.
Needed for Swordfish Class of Service / Line of Service schema files.
=> Add LineOfService as a recognized base_type (equiv to Resource) to generate $ref in json files

doc-generator/doc_formatter/markdown_generator.py, doc-generator/doc_formatter/property_index_generator.py
=> Doc-generator - Fixes for two crashes using markdown output

doc-generator/locale/doc_generator.pot, doc-generator/locale/en/LC_MESSAGES/doc_generator.po
Adds "Example", "Request Example", and "Response Example". Also updates the
location info for many strings.
=> Update strings for translation.

doc-generator/doc_formatter/property_index_generator.py
=> Update property_index_generator.py to fix Doc Generator build of Property guides

odata-csdl-validator/odata_validator.py
=> Update odata_validator.py to fix python syntax warnings

redfish-repo-test/csdl-syntax-test.js, redfish-repo-test/package.json
Updating allowable units and enums
=> Repo test updates

redfish-repo-test/csdl-syntax-test.js, redfish-repo-test/package.json
Adding support for the kVAh units.
=> Added new exceptions for units of measure

doc-generator/doc_formatter/doc_formatter.py, doc-generator/doc_formatter/markdown_generator.py, doc-generator/doc_formatter/property_index_generator.py, doc-generator/format_utils/format_utils.py, doc-generator/format_utils/html_utils.py, doc-generator/tests/samples/action_payloads/expected_output/markdown.md, doc-generator/tests/samples/fragments/expected_output.md, doc-generator/tests/samples/fragments/expected_slate_output.md, doc-generator/tests/samples/generate_docs_cases/general/expected_output/markdown_output.md, doc-generator/tests/samples/generate_docs_cases/general/expected_output/markdown_with_table_numbering_output.md, doc-generator/tests/samples/generate_docs_cases/general/expected_output/slate_output.md, doc-generator/tests/samples/generate_docs_cases/integer/expected_output/markdown_output.md, doc-generator/tests/samples/generate_docs_cases/integer/expected_output/slate_output.md, doc-generator/tests/samples/generate_docs_cases/required/expected_output/markdown_output.md, doc-generator/tests/samples/generate_docs_cases/required/expected_output/slate_output.md, doc-generator/tests/samples/pattern_properties/expected_output/MessagesPropertyDetails.md, doc-generator/tests/samples/referenced_objects/network_sample_output/output.md, doc-generator/tests/test_action_response.py, doc-generator/tests/test_release_history.py
Still need to address unit test failures before merging
=> Adding column width adjustments to doc generators for usage with Markdown interpreters

json-to-openapi-converter/json-to-yaml.py
=> Fixed 'required' properties in the odata resource

redfish-repo-test/csdl-syntax-test.js, redfish-repo-test/package.json
This will add checks to make sure we aren't putting weird release strings in
=> Add Release String Term Checks

redfish-repo-test/csdl-syntax-test.js
=> Add URI Checks

redfish-repo-test/csdl-syntax-test.js, redfish-repo-test/package.json
Enhances the updatable resource check to allow for writable common objects.
=> Added check for writable common objects

redfish-repo-test/csdl-syntax-test.js
Adds unit test that verifies type attribute to conform with following requirements
• A qualified name that references an enum type element.
• A qualified name that references a complex type element.
• A primitive data type.
• An array of the previous names or types by using the Collection term
#422
=> Add unit test to csdl-syntax-test that verifies Type Attribute

redfish-repo-test/dsp2046-test.js, redfish-repo-test/package.json
Fixes https://github.com/DMTF/Redfish/issues/5225
=> Add DSP2046 checks

registry-doc-generator/README.md, registry-doc-generator/registry-doc-generator.py
=> Added option to save registry document as a CSV

doc-generator/doc_formatter/doc_formatter.py
=> Fixed assembling of required property term for arrays

csdl-to-json-convertor/csdl-to-json.py
Removed trailing whitespace from `writeOnly` property name.
=> Corrected `writeOnly` property name

redfish-repo-test/csdl-syntax-test.js
Changes to work for latest Swordfish build
=> Update csdl-syntax-test.js with changes for Swordfish

csdl-to-json-convertor/dmtf-config.json, doc-generator/doc_formatter/html_generator.py, doc-generator/doc_formatter/markdown_generator.py
These patterns were updated in Redfish JSON schema output
=> Updated known `pattern` value for UUID and Duration formats

json-to-openapi-converter/json-to-yaml.py
Stemming from request here: https://redfishforum.com/thread/885/failed-generate-client-swagger-codegen
=> Updated OpenAPI tool to remove all anyOf instances to avoid client bloat

doc-generator/doc_formatter/doc_formatter.py
Adds separate sections for UseCases when generating from a profile.
[example_output.zip](https://github.com/DMTF/Redfish-Tools/files/12770312/example_output.zip)
=> Added compatibility for UseCases

json-to-openapi-converter/json-to-yaml.py
=> Moved the usage of 'parameters' from operations to 'operation objects' to 'path items'

json-to-openapi-converter/json-to-yaml.py
=> Fixed null usage in new oneOf statements

json-to-openapi-converter/json-to-yaml.py
Addresses conformance issue highlighted here: https://github.com/DMTF/Redfish-Service-Validator/issues/588
=> Updated building of OpenAPI definitions to preserve hardened pointers to schema definition for auto-expanded resources

redfish-oem-integrator/LICENSE.md, redfish-oem-integrator/README.md, redfish-oem-integrator/contoso-example-config.json, redfish-oem-integrator/contoso-oem-extensions.json, redfish-oem-integrator/redfish-oem-integrator.py
Migrating the Redfish OEM Integrator tool to the public repo
=> Migrating the Redfish OEM Integrator tool to the public repo

redfish-oem-integrator/README.md, redfish-oem-integrator/contoso-example-config.json, redfish-oem-integrator/contoso-oem-annotation-bindings.json, redfish-oem-integrator/redfish-oem-integrator.py
=> Issue #495: Add support for injecting Annotations in Json Schemas. Also add support for specifying min and max lengths for string properties.

redfish-oem-integrator/redfish-oem-integrator.py
=> Fixed sort ordering
